name: Deploy to neocities

# Deploy only when a new tag is pushed
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Triggers on version tags, e.g., v1.0.0, v2.3.4

concurrency:
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install deps and build
      run: |
        npm i
        npm run blog:build
    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v3
      with:
        api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: false
        neocities_supporter: false
        preview_before_deploy: true
        dist_dir: _site